name: Test API

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Test NewsAPI Connectivity
        run: |
          curl -s "https://newsapi.org/v2/everything?q=technology&apiKey=${{ secrets.NEWS_API_KEY }}"
