name: Fetch News and Push to SQS

on:
  schedule:
    - cron: "0 */8 * * *"  # Run every 8 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          set -x  # Debug mode (shows each command)
          python -m pip install --upgrade pip
          pip install -r local/requirements.txt --verbose  # Ensure path is correct

      - name: Run News Fetch Script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SQS_QUEUE_URL: ${{ secrets.SQS_QUEUE_URL }}
        run: |
          set -x  # Debug mode
          cd local
          python news_fetcher.py
